version: '3.8'
services:
  bikeshop-sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "BikeShopPassword@2024"
    ports:
      - "1433:1433"
    container_name: bikeshop-sql